const zuColor = ['black', 'limegreen', 'deepskyblue', 'blueviolet', 'orange', 'red'];

export const zus = [
  {
    name: '人族',
    initLevel: 0,
    borthNum: 10000,
    levelUpRate: 50n,
    powerRate: 50,
    color: zuColor[0],
  },
  {
    name: '兽族',
    initLevel: 0,
    borthNum: 20000,
    levelUpRate: 20n,
    powerRate: 52,
    color: zuColor[0],
  },
  {
    name: '虫族',
    initLevel: 0,
    borthNum: 50000,
    levelUpRate: 5n,
    powerRate: 5,
    color: zuColor[0],
  },
  {
    name: '羽族',
    initLevel: 0,
    borthNum: 15000,
    levelUpRate: 30n,
    powerRate: 53,
    color: zuColor[0],
  },
  {
    name: '海族',
    initLevel: 0,
    borthNum: 30000,
    levelUpRate: 20n,
    powerRate: 45,
    color: zuColor[0],
  },
  {
    name: '精灵族',
    initLevel: 1,
    borthNum: 2000,
    levelUpRate: 50n,
    powerRate: 99,
    color: zuColor[1],
  },
  {
    name: '矮人族',
    initLevel: 1,
    borthNum: 4000,
    levelUpRate: 30n,
    powerRate: 80,
    color: zuColor[1],
  },
  {
    name: '不死族',
    initLevel: 2,
    borthNum: 1000,
    levelUpRate: 49n,
    powerRate: 60,
    color: zuColor[2],
  },
  {
    name: '修罗族',
    initLevel: 2,
    borthNum: 200,
    levelUpRate: 40n,
    powerRate: 160,
    color: zuColor[2],
  },
  {
    name: '鬼族',
    initLevel: 2,
    borthNum: 500,
    levelUpRate: 45n,
    powerRate: 125,
    color: zuColor[2],
  },
  {
    name: '元素族',
    initLevel: 2,
    borthNum: 200,
    levelUpRate: 65n,
    powerRate: 165,
    color: zuColor[2],
  },
  {
    name: '龙族',
    initLevel: 3,
    borthNum: 50,
    levelUpRate: 60n,
    powerRate: 215,
    color: zuColor[3],
  },
  {
    name: '凤族',
    initLevel: 3,
    borthNum: 70,
    levelUpRate: 65n,
    powerRate: 210,
    color: zuColor[3],
  },
  {
    name: '神族',
    initLevel: 4,
    borthNum: 5,
    levelUpRate: 55n,
    powerRate: 280,
    color: zuColor[4],
  },
  {
    name: '仙族',
    initLevel: 4,
    borthNum: 10,
    levelUpRate: 75n,
    powerRate: 255,
    color: zuColor[4],
  },
];
// gray forestgreen  springgreen  mediumblue aqua  blueviolet gold darkgoldenrod  maroon red
export const levelConfig = [
  {
    power: 1,
    name: '凡体',
    rate: 2048n, // 2048 / 100000
    color: 'gray',
  },
  {
    power: 10,
    name: '地仙',
    rate: 1024n,
    color: 'forestgreen',
  },
  {
    power: 100,
    name: '天仙',
    rate: 512n,
    color: 'springgreen',
  },
  {
    power: 1000,
    name: '玄仙',
    rate: 256n,
    color: 'mediumblue',
  },
  {
    power: 10000,
    name: '真仙',
    rate: 128n,
    color: 'aqua',
  },
  {
    power: 100000,
    name: '金仙',
    rate: 64n,
    color: 'blueviolet',
  },
  {
    power: 1000000,
    name: '太乙金仙',
    rate: 32n,
    color: 'gold',
  },
  {
    power: 10000000,
    name: '大罗金仙',
    rate: 16n,
    color: 'darkgoldenrod',
  },
  {
    power: 100000000,
    name: '仙王',
    rate: 8n,
    color: 'maroon',
  },
  {
    power: 1000000000,
    name: '仙帝',
    rate: 0n,
    color: 'red',
  },
];
